version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  webhook-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
